### ISSUE TITLE
Chisel issue

### ISSUE THREAD

**Issue by devryb** [Pokefenn/Chisel#46] opened 2014-09-06 23:35 UTC
Open the chisel gui and place a block or stack of blocks in the center that will give the chisel in your hotbar the indication that blocks are placed in it.
Close the gui with the blocks still inside.
Open the gui and place an item that won't normally give the chisel a gui representation in your hotbar that an item is inside and close the gui. (taking out the blocks you had placed in there previously)
You will see that the previous block you placed in the chisel will still show in your hotbar representation.
Open the gui again and you will see the blocks that were placed originally in there and you can pull them out and use them normally, effectively duping the original blocks. (Sacrificing the item you placed in the second step)

**Comment by EoD** [comment] 2014-09-14 18:33
Can you give examples of blocks you used? I cannot reproduce the issue here.

**Comment by Pokefenn** [comment] 2014-09-15 10:11
Closing because unable to reproduce. Please post more information, including a video or pictures if possible.

**Closed as completed by Pokefenn** 2014-09-15 10:11 UTC

**Comment by EoD** [comment] 2014-10-02 08:38
@devryb if you are using the 1.6 version of thet mod, there is a hotfix release https://github.com/EoD/Chisel-Legacy/releases
