### ISSUE TITLE
Wrong texture on block

### ISSUE THREAD

**Issue by ghost** [Pokefenn/Chisel#33] opened 2014-08-08 14:20 UTC
I've seen this many times, its a bug for sure:
![2014-08-08_16 18 03](https://cloud.githubusercontent.com/assets/6962254/3857771/1d97033c-1f07-11e4-906e-488259ac6625.png)

**Comment by Pokefenn** [comment] 2014-08-08 14:43
Context less and I'm unable to reproduce.
Please give bug reports more information, how are we meant to fix things like that if we have no idea about it?...

**Comment by Pokefenn** [comment] 2014-08-09 17:33
Closing due to lack of information or anything.

**Closed as completed** 2014-08-09 17:32 UTC
