### ISSUE TITLE
ClassNotFoundException in the console whilst loading the game

### ISSUE THREAD

**Issue by Painstouch** [Pokefenn/Chisel#49] opened 2014-09-10 09:10 UTC
https://gist.github.com/Painstouch/c5f9add43f51133a24ea

**Comment by EoD** [comment] 2014-09-11 11:11
- Does it also crash if you remove Chisel and keep NumiRP?
- Does it crash if you keep Chisel and remove NumiRP?

NumiRP seems to be from https://github.com/Numerios/NumiRP

**Comment by Painstouch** [comment] 2014-09-11 12:11
It doesn't crash the game at all at the moment, it's just an excerpt from the console whilst loading the game.
Also, I don't have NumiRP installed, not that I am aware of or being able to see it in the mods section.

**Comment by ghost** [comment] 2014-09-13 20:17
The error comes up because chisel is searching for the main mod class for compat's sake.  Don't worry about it- nothing went wrong.

**Comment by EoD** [comment] 2014-09-14 18:19
Actually, this has already been fixed in b5d2c4aee28ebe0bf429ae51c2916c491c1c0a7c and a duplicate of #41 .

**Comment by Pokefenn** [comment] 2014-09-15 10:09
Redundant "bug" report that people have "reported" loads of times already.

**Closed as completed by Pokefenn** 2014-09-15 10:09 UTC
